### ISSUE TITLE
best sequenceに同じ符合が出るケース

### ISSUE THREAD

**Issue by bleu48** [ymgaq/Pyaq#1]
対応環境ではないのですが，Windows10 Python3.5上です。
best sequenceに同じ符合が続いて出るケースがあり，おかしくなります。
そもそもlegalではないのでおかしいのですがちょっと原因を探れておりません。
心当たりないでしょうか。

**Comment by ymgaq** [comment]
ご指摘ありがとうございます。
たまに置換表が壊れて、非連続な局面に繋がって迷子になることは確認しております。一応処置をしたのですが、もし頻出して再現するようでしたら、思考ログを貼っていただける原因特定に役立ちます。

**Comment by bleu48** [comment]
以下，最速で壊れるケースです。
legalが呼ばれていないので置換表破壊なんでしょうか。

PS C:\work\pyaq\Pyaq> python .\pyaq.py --self
2018-02-16 06:45:50.256137: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX

move count=1: left time=0.0[sec] evaluated=74
|move|count  |rate |value|prob | best sequence
|E6  |    522| 59.1| 65.1| 17.5| E6 ->E3 ->G5 ->G3 ->C6 ->E8 ->F7 ->F8
|F6  |     47| 58.2| 55.6| 20.0| F6 ->E3 ->F5 ->G3 ->F3 ->D4
|E5  |      1| 42.1| 42.1| 33.3| E5 ->E3 ->F5 ->G3 ->F3 ->D4
|D6  |      1| 52.0| 52.0|  6.7| D6
|D5  |      1| 33.5| 33.5|  5.2| D5
|F7  |      1| 45.3| 45.3|  4.2| F7
|D4  |      1| 37.4| 37.4|  3.7| D4
|F5  |      1| 49.7| 49.7|  2.0| F5
   A  B  C  D  E  F  G  H  J
 9 .  .  .  .  .  .  .  .  .  9
 8 .  .  .  .  .  .  .  .  .  8
 7 .  .  .  .  .  .  .  .  .  7
 6 .  .  .  . [X] .  .  .  .  6
 5 .  .  .  .  .  .  .  .  .  5
 4 .  .  .  .  .  .  .  .  .  4
 3 .  .  .  .  .  .  .  .  .  3
 2 .  .  .  .  .  .  .  .  .  2
 1 .  .  .  .  .  .  .  .  .  1
   A  B  C  D  E  F  G  H  J


move count=2: left time=0.0[sec] evaluated=92
|move|count  |rate |value|prob | best sequence
|E4  |    449| 35.9| 30.9| 74.8| E4 ->C5 ->G4 ->D3 ->F4 ->D4 ->F7 ->E7
|E3  |     26| 27.2| 33.8| 14.6| E3 ->C5 ->G4 ->D3 ->F4 ->D4 ->F7 ->E7
|F4  |     18| 26.9| 27.8|  3.3| F4 ->E4 ->E3 ->D3 ->D4 ->E3 ->F5 ->G4
|F3  |     18| 26.9| 31.6|  2.1| F3 ->E4 ->E3 ->D3 ->D4 ->E3 ->F5 ->G4
   A  B  C  D  E  F  G  H  J
 9 .  .  .  .  .  .  .  .  .  9
 8 .  .  .  .  .  .  .  .  .  8
 7 .  .  .  .  .  .  .  .  .  7
 6 .  .  .  .  X  .  .  .  .  6
 5 .  .  .  .  .  .  .  .  .  5
 4 .  .  .  . [O] .  .  .  .  4
 3 .  .  .  .  .  .  .  .  .  3
 2 .  .  .  .  .  .  .  .  .  2
 1 .  .  .  .  .  .  .  .  .  1
   A  B  C  D  E  F  G  H  J

Traceback (most recent call last):
  File ".\pyaq.py", line 57, in <module>
    move, _ = tree.search(b, 0, clean=clean)
  File "C:\work\pyaq\Pyaq\search.py", line 214, in search
    self.search_branch(b_cpy, self.root_id, route)
  File "C:\work\pyaq\Pyaq\search.py", line 158, in search_branch
    value = -self.search_branch(b, next_id, route)
  File "C:\work\pyaq\Pyaq\search.py", line 158, in search_branch
    value = -self.search_branch(b, next_id, route)
  File "C:\work\pyaq\Pyaq\search.py", line 158, in search_branch
    value = -self.search_branch(b, next_id, route)
  [Previous line repeated 991 more times]
  File "C:\work\pyaq\Pyaq\search.py", line 134, in search_branch
    b.play(next_move, False)
  File "C:\work\pyaq\Pyaq\board.py", line 250, in play
    if not self.legal(v):
  File "C:\work\pyaq\Pyaq\board.py", line 204, in legal
    if v == PASS:
RecursionError: maximum recursion depth exceeded in comparison

**Comment by bleu48** [comment]
追伸：
Windows 10 WSL Ubuntu 16.04 python 2.7 では問題ないことを確認しました（cuda使えません）
python のバージョンの問題かもしれません

**Comment by ymgaq** [comment]
なるほど、ありがとうございます。私の手元環境（python2.7）でも再現しないので、python2/3の何らかの挙動の違いによる可能性が高いです。その観点で調べてみます。

**Comment by bleu48** [comment]
hashが当たってますね。
board.pyに
import hashlibを加えて
    def hash(self):
        return (int(hashlib.md5(self.color.data).hexdigest()[:4], 16) ^
            int(hashlib.md5(self.prev_color[0].data).hexdigest()[:4], 16) ^ self.turn)
とか編集したら重いけど動きました。

**Comment by ymgaq** [comment]
ありがとうございます、私もちょうどhashが原因ではないかと思い当たったところでした。
適宜修正したいと思います。
